- CRISPResso2/CRISPRessoPooledCORE.py
> args.trimmomatic_command

- CRISPResso2/CRISPRessoPlot.py
Related to issue #61
This happens when N_ROWS < 1 which I assume has something to do with no results -> negative control
> Fix a bug when generating compare plot

- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoShared.py
These changes implement separating reads to their corresponding amplicons via
Python instead of through awk. This is to get around the maximum number of open
files that is limited on many operating systems.
> Alt pooled processing implementation

- .gitignore
- CRISPResso2/CRISPRessoPooledCORE.py
I thought that this would be good to get in before the version bump.
> Fix writing in CRISPRessoPooled

- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoWGSCORE.py
Ticket: https://github.com/pinellolab/CRISPResso2/issues/141
> BugFix: database_id referenced before declared.

- CRISPResso2/CRISPRessoAggregateCORE.py
- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCompareCORE.py
- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoPooledWGSCompareCORE.py
- CRISPResso2/CRISPRessoReport.py
- CRISPResso2/CRISPRessoWGSCORE.py
I believe that these changes have moved all of the remaining objects that were at the top level of the `crispresso2_info` object down to their appropriate levels.
> Update crispresso info again

- CRISPResso2/CRISPRessoPlot.py
Typo causing error in certain modes.
> Update ylabel_values -> y_label_values

- CRISPResso2/CRISPRessoCompareCORE.py
@Snicker7 this should fix the issue that we were running into when comparing the same runs.
> Fix bug when comparing two samples with the same name.

- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoCompareCORE.py
- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoPooledWGSCompareCORE.py
- CRISPResso2/CRISPRessoShared.py
- CRISPResso2/CRISPRessoWGSCORE.py
- README.md
Add a command line option to zip the output results folder.
> Add `zip_output`

- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoShared.py
- CRISPResso2/CRISPRessoWGSCORE.py
- Add several checks for amplicon uniqueness.
- Fixes a bug with CRISPRessoBatch plotting
- Fixes future pandas deprecation of df.append
> Batch amplicon plots

- CRISPResso2/CRISPRessoPooledCORE.py
Looks like these changes fixed #264, do we want to add the `try... finally` around the cached pandas operation @kclem? Or should we not worry about it?
> Fix CRISPRessoPooled bam input

- README.md
I have suffered enough trying to debug my installation, so hopefully this helps someone else.
> Add snippet about installing CRISPResso2 via bioconda on Apple silicon

- scripts/plotCustomAllelePlot.py
Update type of 'max_rows' param to int
Fix location of 'args' in crispresso2_info object
> Update plotCustomAllelePlot.py script for #292

- CRISPResso2/CRISPRessoBatchCORE.py
P.S. I forgot to do a squash merge, so we can see how this affects the fork history...
> Removing format string print statements, fixes #295

- .github/envs/test_env.yml
- .github/workflows/.pylintrc
- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- CRISPResso2/CRISPRessoPlot.py
These changes will add a Github Action so that the unit tests are run on each push. Also, this fixes the issue where only part of the characters on allele quilt plots are plotted. 
Closes #384 and #345.
> Run unit tests via Github Actions and fix matplotlib character issue

- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoWGSCORE.py
* refactor to call method on DataFrame, rather than Series. Removes warning.
* Fix pandas future warning in CRISPRessoWGS
---------
> Fix batch mode pandas warning. (#70)

- .github/workflows/integration_tests.yml
- CRISPResso2/CRISPRessoAggregateCORE.py
- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoMultiProcessing.py
- CRISPResso2/CRISPRessoReports/CRISPRessoReport.py
- CRISPResso2/CRISPRessoReports/templates/shared/partials/fig_reports.html
This PR fixes a few bugs where the plots weren't showing up properly when multiple amplicons were present. It also enhances the error handling of the plots by not failing the entire run when an exception is thrown during plotting, but still allowing the other plots and report to be generated.
> Fix plots and improve plot error handling

- .github/envs/test_env.yml
- CRISPResso2/CRISPRessoPlot.py
This includes implementing the behavior for `plot_alleles_heatmap_hist` and reduces some slight duplication.
> Cole asymmetrical cut point

- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoReports/templates/batchReport.html
- CRISPResso2/CRISPRessoReports/templates/report.html
- CRISPResso2/CRISPRessoReports/templates/shared/partials/fig_summaries.html
- CRISPResso2/CRISPRessoShared.py
- CRISPResso2/args.json
- tests/unit_tests/test_CRISPRessoShared.py
This implements zooming on d3 plots and improves sgRNA placement.
> d3 plot enhancements

- .github/workflows/integration_tests.yml
- CRISPResso2/CRISPRessoAggregateCORE.py
- CRISPResso2/CRISPRessoReports/CRISPRessoReport.py
This fixes a bug https://github.com/pinellolab/CRISPResso2/issues/469 in CRISPRessoAggregate. It also adds the command used to the `CRISPResso2Aggregate_info.json` file and makes the order of the aggregated runs deterministic.
> Fix CRISPRessoAggregate bug and other improvements (#95)

- CRISPResso2/CRISPRessoShared.py
This will add a progress percentage indicator in the CLI output.
> Display percentages in the CLI output

- CRISPResso2/CRISPRessoMultiProcessing.py
This PR doesn't start the processor pool when running with only a single thread.
> No processor pool when running in single thread 

- CRISPResso2/CRISPResso2Align.c
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoCOREResources.c
- CRISPResso2/CRISPRessoCOREResources.pyx
This PR implements the alignment data structure using slots instead of a dictionary. For large datasets, this results in lower memory usage.
> Slots implementation
