- CRISPResso2/CRISPRessoPooledCORE.py
Fixes the following error at the end of the process:
`KeyError: ('#name', u'occurred at index TaFielderBADH2-1a')`
> If the name column is called 'name', refer to it as 'name', not '#name'.

- CRISPResso2/CRISPRessoCORE.py
Addresses terminating ERROR: Filesize would require ZIP64 extensions when trying to write compressed allele frequency tables > 2 GB
> ZipFile: set allowZip64=True to write larger allele frequency tables

- CRISPResso2/CRISPRessoCompareCORE.py
I encountered the following error when running CIRSPRessoCompare:
```
ERROR: global name 'nan' is not defined 
```
I tried running with `--debug` to get a better stacktrace but I did not seem to provide much more detail. After a bit of searching I think this is the isssue.
> fix missing import path on NaN

- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoShared.py
These changes implement separating reads to their corresponding amplicons via
Python instead of through awk. This is to get around the maximum number of open
files that may be limited on some operating systems.
This alternate implementation will be used if more than 50 amplicons are processed in CRISPRessoPooled using the 'Amplicons only' mode (not aligning to genome)
> Alt CRISPRessoPooled processing implementation

- setup.py
Remove the argparse dependency from setup.py because argparse is a standard module in Python 3.
> Remove argparse dependency

- CRISPResso2/filterFastqs.py
This commit fixes the filterFastqs script by properly casting to strings (from
bytes) in the appropriate places. It also replaces the deprecated
`np.fromstring` function with `np.frombuffer`.
> Fix filterFastqs

- scripts/plotCustomAllelePlot.py
- pass plot_center as a parameter to plot_alleles_tables_from_folder and replace args.plot_center references in function accordingly
- substitute iteritems() with items() for insertion_dict.items().
> minor bug fixes for plotCustomAllelePlot.py to work with Python3

- CRISPResso2/CRISPRessoBatchCORE.py
I put `OUTPUT_DIRECTORY` in quotes to handle directories with spaces.
> CRISPRessobatch: put directory in quotes

- CRISPResso2/CRISPRessoCORE.py
When there are no reads (i.e. global_MODIFIED_FRAMESHIFT +
global_MODIFIED_NON_FRAMESHIFT + global_NON_MODIFIED_NON_FRAMESHIFT == 0) there
was a bug when trying to compute the pie chart, because all of the values in the
pie chart are 0. This fix, will make sure that there is at least one read in
order for the plot to bee constructed properly.
Closes #224
> Don't run global frameshift plot when there are no modified reads

- CRISPResso2/CRISPRessoPooledCORE.py
Also, raise an exception (instead of incorrectly executing) when there are not
enough matched parameters in the pooled input file.
> Fix bug when name is provided instead of amplicon_name in pooled input file

- CRISPResso2/CRISPRessoBatchCORE.py
There was a bug that I introduced in CRISPRessoBatch when the sgRNA intervals are equal. This commit fixes it!
> Fix for aggregate plots in Batch mode

- CRISPResso2/CRISPRessoAggregateCORE.py
- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoMultiProcessing.py
These changes refactor how parallel plots are invoked, hopefully making it cleaner and less bug prone.
> Parallel plot refactor

- CRISPResso2/CRISPRessoBatchCORE.py
This fixes an incorrectly named allele quilt plot input in CRISPRessoBatch.
> Fix batch quilt plot name

- CRISPResso2/CRISPRessoCORE.py
Somehow I missed this typo when testing the plot refactoring.
> Fix typo of CRISPResssoPlot when plotting nucleotide quilt

- CRISPResso2/CRISPResso2Align.pyx
- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoPlot.py
In the most recent version of numpy (1.24) some of the types have been deprecated. This commit fixes these errors.
> Fix deprecated numpy type names (fixes #269)

- CRISPResso2/CRISPRessoPooledCORE.py
- README.md
Fixes to custom headers in CRISPRessoPooled
> CRISPRessoPooled custom header fix

- CRISPResso2/CRISPRessoWGSCORE.py
Sometimes some of the libraries that samtools depends on don't have the correct
version information (happens in Docker), and as such samtools will report this to stderr when run.
Because we pipe the output of samtools, we expect it to be valid SAM format, but
when these library version messages are reported, it breaks CRISPRessoWGS.
This also fixes a bug where a comma was missing in suppressing the parameters on CRISPRessoWGS. Before this fix, `['bam_input', 'bam_chr_locfastq_r1', 'fastq_r2', 'amplicon_seq', 'amplicon_name']` was being passed as `suppress_params` to `CRISPRessoShared.getCRISPRessoArgParser()`. After the fix, `['bam_input', 'bam_chr_loc', 'fastq_r1', 'fastq_r2', 'amplicon_seq', 'amplicon_name']` is being passed as `suppress_params`. This change allows `bam_chr_loc` and …
> Fix samtools piping

- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoShared.py
Adds two parameters to control alignment of pegRNA components: `--prime_editing_gap_open_penalty` and `--prime_editing_gap_extend_penalty`.
CRISPResso checks to see whether the pegRNA spacer and extension sequence are in the correct orientation, but sometimes they could align in the incorrect orientation with a higher score (e.g. via insertion of multiple gaps, whereas a single long gap would be preferred). Introducing these two parameters allows users to adjust the alignment parameters specifically for these prime-editing checks without adjusting the global alignment parameters which will be applied to reads that are aligned to the WT reference/prime-editing reference sequences. 
The new prime_editing_gap_open_penalty is set to -50, a higher gap open penalty than the default …
> Prime editing alignment params

- CRISPResso2/CRISPRessoPlot.py
The new version of Matplotlib (3.8) has a new way to [input colors using tuples](https://matplotlib.org/stable/users/prev_whats_new/whats_new_3.8.0.html#id14) which breaks this function unless the colors are a list.
This PR fixes it.
> Fix for recent Matplotlib v3.8

- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoMetaCORE.py
- CRISPResso2/CRISPRessoShared.py
- scripts/count_sgRNA_specific_edits.py
This PR includes:
- storing the sgRNA-specific editing locations in the crispresso2_info object
- a script to parse through an allele table output from a completed CRISPResso run (`--write_detailed_allele_table` flag required) to count edits in each sgRNA separately.
I don't have a good double-edited sample handy, but it can be run on the demo HDR data [hdr.fastq.gz](http://crispresso.pinellolab.org/static/demo/hdr.fastq.gz) using the command:
```
CRISPResso -r1 hdr.fastq.gz -a acatttgcttctgacacaactgtgttcactagcaacctcaaacagacaccatggtgcatctgactcctgTggagaagtctgccgttactgccctgtggggcaaggtgaacgtggatgaagttggtggtgaggccctgggcaggttggtatcaaggtta -e acatttgcttctgacacaactgtgttcactagcaacctcaaacagacaccatggtgcaCctgactccGgaggagaagtctgccgttactgcGctgtggggcaaggtgaacgtggatgaagttggtggtgaggccctgggcaggttggtatcaagg …
```
> Enable quantification by sgRNA

- CRISPResso2/CRISPRessoPlot.py
In a new version of Matplotlib, colors are represented differently. When the color is represented as a tuple it expects to have an alpha value, but when it is represented as a list it produces the expected behavior.
> Fix Matplotlib breaking change issue

- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoCompareCORE.py
- CRISPResso2/CRISPRessoPlot.py
This PR (by @mbowcut2) refactors the code so that the future Panadas warnings are ignored.
> Remove future Pandas warnings and sort CRISPRessoCompare tables

- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoShared.py
- CRISPResso2/CRISPRessoWGSCORE.py
* Extract out split_interleaved_fastq function to CRISPRessoShared
* Implement splitting interleaved fastq files in CRISPRessoPooled
* Suppress split_interleaved_input from CRISPRessoWGS parameters
* Suppress other parameters in CRISPRessoWGS
* Move where interleaved fastq files are split to be trimmed properly
> Fix interleaved fastq input in CRISPRessoPooled and suppress CRISPRessoWGS params

- CRISPResso2/CRISPRessoCORE.py
* - Fixed references to ref_names_for_pe
* removed extra tabs
* trying to match empty line, no tabs
* - changed references to ref_names[0]
* Mckay/pd warnings (#45)
* refactor errors='ignore' to try except
* refactored integer slice to iloc[]
* moved to_numeric try except to function
* Refactor to_numeric_ignore_errors to to_numeric_ignore_columns
This change is slightly cleaner because it addresses the root issue that some columns are strings (and can therefore not be converted to numeric types). Now if an error does occur when converting the dfs to numeric types it won't be swallowed up.
* Add documentation to to_numeric_ignore_columns
---------
---------
> Fix #367, reads only align to prime edited amplicon, not to reference

- .github/envs/test_env.yml
- .github/workflows/integration_tests.yml
- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- CRISPResso2/CRISPRessoCORE.py
This PR runs all integration tests using Github Actions on each push to a branch.
> Run integration tests on every push

- .github/workflows/integration_tests.yml
- .github/workflows/pylint.yml
- .github/workflows/pytest.yml
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoReports/README.md
- CRISPResso2/CRISPRessoReports/templates/batchReport.html
- CRISPResso2/CRISPRessoReports/templates/multiReport.html
- CRISPResso2/CRISPRessoReports/templates/pooledReport.html
- CRISPResso2/CRISPRessoReports/templates/wgsReport.html
* Move read filtering to after merging
This is in an effort to be consistent with the behavior and results of CRISPRessoPooled.
* Properly assign the correct file names for read filtering
* Add space around operators
> Move read filtering to after merging in CRISPResso

- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoShared.py
- tests/unit_tests/test_CRISPRessoCORE.py
- tests/unit_tests/test_CRISPRessoShared.py
* Mckay/pd warnings (#45)
* refactor errors='ignore' to try except
* refactored integer slice to iloc[]
* moved to_numeric try except to function
* Refactor to_numeric_ignore_errors to to_numeric_ignore_columns
This change is slightly cleaner because it addresses the root issue that some columns are strings (and can therefore not be converted to numeric types). Now if an error does occur when converting the dfs to numeric types it won't be swallowed up.
* Add documentation to to_numeric_ignore_columns
---------
* Extract out quantification window coordinate function
* Refactor get_quant_window_coordinates function into two
The rationale behind this is that the behavior around the cloned amplicon is quite different than if the qwc are specified directly for the amplicon.
* Handling qwc: …
> Fix the assignment of multiple quantification window coordinates

- README.md
The spaces used in the `docker run` command may look the same, but they are actually different characters. While a regular space is represented by the ASCII character 0x20, the command provided in the current `README.md` is using a non-breaking space (U+00A0 or 0xC2 0xA0 in UTF-8). Some shells treat `docker[non-breaking space]run` as a single word, causing the command to fail.
For references:
https://www.scivision.dev/hex-code-c2a0-non-breaking-space-markdown/
https://community.notepad-plus-plus.org/topic/19862/replace-non-breaking-space-utf-8-c2-a0
https://news.ycombinator.com/item?id=27896856
Before Fix:
```bash
$ docker run -v ${PWD}:/DATA -w /DATA -i pinellolab/crispresso2 CRISPResso -h
docker run: command not found
```
After the fix:
```bash
$ docker run -v ${PWD}:/DATA -w /DATA -i …
```
> fix `space` character in README

- .github/workflows/integration_tests.yml
- CRISPResso2/CRISPRessoReports/CRISPRessoReport.py
- CRISPResso2/CRISPRessoReports/templates/report.html
* Replace Jinja2 PackageLoader with FileSystemLoader
The PackageLoader doesn't work with a fairly recent version of Jinja2 (3.0.1) and Python 3.9. Replacing with FileSystemLoader work with the older version and the latest version.
* Fix undefined variable `amplicon_name` in report template
* Revert plot_11a update
* Update intedration test branch
* Update branch for integration tests
> Fix Jinja2 undefined variables

- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoCompareCORE.py
- CRISPResso2/CRISPRessoMetaCORE.py
- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoPooledWGSCompareCORE.py
- CRISPResso2/CRISPRessoReports/CRISPRessoReport.py
- CRISPResso2/CRISPRessoReports/templates/report.html
- CRISPResso2/CRISPRessoWGSCORE.py
* Replace Jinja2 PackageLoader with FileSystemLoader
The PackageLoader doesn't work with a fairly recent version of Jinja2 (3.0.1) and Python 3.9. Replacing with FileSystemLoader work with the older version and the latest version.
* Fix undefined variable `amplicon_name` in report template
* Refactor logging Jinja2 undefined variable warnings
* Revert plot_11a update
* Update intedration test branch
* Update jinja to warn on undefined but not fail. Fix all undefined warnings
* Fix github integration tests ref
* One more undefined variable
---------
> Cole/refactor jinja undefined (#66)

- .github/envs/test_env.yml
- .github/workflows/integration_tests.yml
- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoReports/CRISPRessoReport.py
- CRISPResso2/CRISPRessoReports/jinja_partials.py
- README.md
- setup.py
This extracts the functionality needed from `jinja_partials` so that it is no longer a dependency. This also fixes the errors when merging paired end reads using CRISPRessoPooled.
> Extract `jinja_partials` and fix CRISPRessoPooled fastp errors

- CRISPResso2/CRISPRessoAggregateCORE.py
- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoCompareCORE.py
- CRISPResso2/CRISPRessoMetaCORE.py
- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoPooledWGSCompareCORE.py
- CRISPResso2/CRISPRessoReports/templates/batchReport.html
- CRISPResso2/CRISPRessoReports/templates/shared/partials/fig_summaries.html
- CRISPResso2/CRISPRessoShared.py
- CRISPResso2/CRISPRessoWGSCORE.py
- tests/unit_tests/test_CRISPRessoCompareCORE.py
This PR includes:
* Update config file logging messages
This removes printing the exception (which is essentially a duplicate), and adds a condition if no config file was provided. Also changes `json` to `config` so that it is more clear.
* Fix divide by zero when no amplicons are present in Batch mode
* Don't append file_prefix to status file name
* Place status files in output directories
* Update tests branch for file_prefix addition
* Load D3 and plotly figures with pro with multiple amplicons
* Fix bug in CRISPRessoCompare with pointing to report datas with file_prefix
Before this fix, when using a file_prefix the second run that was compared would not be displayed as a data in the first figure of the report.
* Import CRISPRessoPro instead of importing the version
When installed via …
> Fix issues with `file_prefix`

- .github/workflows/aws_ecr.yml
- CRISPResso2/CRISPRessoAggregateCORE.py
- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoReports/CRISPRessoReport.py
- CRISPResso2/CRISPRessoReports/templates/batchReport.html
- CRISPResso2/CRISPRessoReports/templates/shared/partials/failed_runs.html
- tests/unit_tests/test_CRISPRessoBatchCORE.py
* Sam/try plots (#71)
* Fix batch mode pandas warning. (#70)
* refactor to call method on DataFrame, rather than Series. Removes warning.
* Fix pandas future warning in CRISPRessoWGS
---------
* Functional
* Cole/fix status file name (#69)
* Update config file logging messages
This removes printing the exception (which is essentially a duplicate), and adds a condition if no config file was provided. Also changes `json` to `config` so that it is more clear.
* Fix divide by zero when no amplicons are present in Batch mode
* Don't append file_prefix to status file name
* Place status files in output directories
* Update tests branch for file_prefix addition
* Load D3 and plotly figures with pro with multiple amplicons
* Update batch
* Fix bug in CRISPRessoCompare with pointing to report …
> Showing sgRNA sequences on hover in CRISPRessoPro

- .github/workflows/aws_ecr.yml
When pushing up to AWS ECR, this will add the `v` to the beginning of the tag.
> Prefix the release Docker tag with a `v`

- .github/workflows/integration_tests.yml
- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/args.json
Now by default, when Pooled is run in mixed-mode (an amplicon file and genome are both provided) CRISPResso will demultiplex the reads that align to the locations in the genomes. This means that reads don't need to align perfectly to the same start and end coordinates. To restore the previous default behavior, one can provide the `--demultiplex_genome_wide` parameter.
> Implement new pooled mixed-mode default behavior

- .github/envs/test_env.yml
- .github/workflows/integration_tests.yml
This speeds up the Github Actions integration tests step.
> Cache conda packages in GIthub Actions

- CRISPResso2/CRISPRessoShared.py
Replace `zcat` with `gunzip -c` in `get_most_frequent_reads` as `gunzip -c` is more reliable on most systems.
> Replace zcat

- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoShared.py
Previously, the --no_rerun flag would re-merge paired reads upon rerunning an incomplete CRISPRessoPooled analysis. This fix avoids this (time-consuming) pre-processing step if it has already been completed.
> Cache read merging step in CRISPRessoPooled on no_rerun

- .github/workflows/integration_tests.yml
- CRISPResso2/CRISPRessoCORE.py
- tests/unit_tests/test_CRISPRessoCORE.py
This PR parallelizes the generation of variant objects while aligning reads from .fastq and .bam files, resulting in more than 8.5x speed increase for runs (One benchmark showed an improvement in run time from 1:23:28 down to 0:09:45 [H:MM:SS])
It refactors the four functions that read from user's input files (process_fastq, process_bam, process_fastq_write_out, and process_single_fastq_write_bam_out). It reads over the files, identifies and counts each unique DNA read, then sends the unique reads in equal chunks to n sub processes for parallel processing, where n is the number of cores specified by the user.
These processes each then stores generated variants in intermediate .tsv files, which are later read to track statistics of the files. If specified, these functions also write out …
> Read Alignment Parallelization (#98)

- .github/workflows/pytest.yml
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/args.json
* Add flexiguid gap open and gap extend customized arguments
* Implement new flexiguide gap extend and gap open parameters
* Point to new test branch for integration tests
* Bump version of setup-miniconda for pytest
* Have flexiguide default penalties match the Needleman Wunsch defaults
* Point test branch back to master
> Add flexiguide alignment parameters

- CRISPResso2/CRISPRessoReports/.github/workflows/pylint.yml
- CRISPResso2/CRISPRessoReports/jinja_partials.py
This updates some linting errors in `jinja_partials` and makes it so that pylint runs in CRISPRessoReports when a PR is opened.
> Update jinja_partials and bring Reports into sync

- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoWGSCORE.py
- CRISPResso2/args.json
- tests/unit_tests/test_CRISPRessoPooledCORE.py
* Add customizable samtools exclude flag
This adds a new parameter, `--samtools_exclude_flags` that allows one to customize which reads are excluded from CRISPRessoWGS and CRISPRessoPooled runs.
> Add customizable samtools exclude flag

- CRISPResso2/CRISPRessoPooledCORE.py
Previously, in CRISPRessoPooled, if two input regions map to the same genomic locus the demultiplexing will create two processes that collide to write on the same file.
For example, if a forward and reverse-complement seq are given as two regions in the in the -f file, they will map to the same location in the genome. When demultiplexing with multiprocessing, the output file will be munged by two processes writing reads to the same file.
With this PR, input is checked to make sure that no amplicons and their reverse complement exist in the input region file. Additionally, just in case, a change is made to avoid munging by two processes by demultiplexing.
> Pooled multi region map fix

- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoShared.py
- tests/unit_tests/test_CRISPRessoShared.py
This PR fixes when get_n_fastq gets an empty gzipped file, it returns 0 instead of throwing an error.
This also fixes a bug when counting reads in fastq files that have no trailing newlines. Now, the function will return the correct number of reads if there is no trailing new line, or multiple trailing new lines.
> Fix `get_n_fastq` function

- CRISPResso2/CRISPRessoAggregateCORE.py
- CRISPResso2/CRISPRessoBatchCORE.py
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoCompareCORE.py
- CRISPResso2/CRISPRessoMetaCORE.py
- CRISPResso2/CRISPRessoPooledCORE.py
- CRISPResso2/CRISPRessoPooledWGSCompareCORE.py
- CRISPResso2/CRISPRessoShared.py
- CRISPResso2/CRISPRessoWGSCORE.py
* Refactor output handling to use 'info' instead of 'print' and remove unused code
* Remove exit after raising of Exception
* Cast chr_id to a string (again)
* Properly scrub invalid characters from beign written to JSON status file
This commit will convert \n, \, and " when being written to the JSON message field because all of those characters will cause the JSON to be invalid.
* Change branch to cole/suppress_printing
* Move test branch back to master
---------
> Suppress printing

- .github/workflows/integration_tests.yml
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoShared.py
- scripts/plotAmbiguous.py
This PR allows for asymmetrical allele plots, which allow for guides to be closer to the edges of the amplicons (the exceptions will no longer be thrown).
> Asymmetrical Allele Plots 

- .github/envs/test_env.yml
- .github/workflows/integration_tests.yml
- CRISPResso2/CRISPRessoCORE.py
- CRISPResso2/CRISPRessoCOREResources.c
- CRISPResso2/CRISPRessoPlot.py
- CRISPResso2/CRISPRessoReports/CRISPRessoReport.py
- CRISPResso2/CRISPRessoReports/templates/report.html
- CRISPResso2/CRISPRessoReports/templates/shared/partials/fig_reports.html
- CRISPResso2/CRISPRessoShared.py
- CRISPResso2/args.json
- Dockerfile
- tests/test_be_df.txt
- tests/unit_tests/test_CRISPRessoCORE.py
This PR adds a new plot when running CRISPResso in Base Editing mode. The plot shows the co-occurrence of edits within the quantification window and, optionally, across the entire amplicon. The plot is an [UpSet plot](https://upset.app/) that illustrates the intersection of various edits across the region.
> Base Editing Bystander edits Plot
